### ISSUE TITLE
Resources 

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/Sparked-Mobile#1]
The User Authentication on mobile is feature to be discussed, it might not be needed or it can also be turned on and off depending on the server structure. 
@abnios

**Comment by OlivierJM** [comment]
Hello @abnios the problem was the navigation, I removed one screen I had added a drawer navigation and I forgot to replace it, it took me time to figure that out because I thought it wasn't logging to meteor. [terminal logs Screenshot ](https://drive.google.com/file/d/1kT1jA6_PVNZpNDeMZRlnoqqjGxPYBJCa/view?usp=sharing)
Notice the line indicated connected to DDP server.
I will have pushed new changes you can pull again

**Comment by OlivierJM** [comment]
@abnios with the current package.json settings you should be able to run `npm run android` and it will run on your simulator

**Comment by abnios** [comment]
I am using a device, I do not have an emulator ...  is it a must to use an emulator to see the terminal DDP connections ??

**Comment by OlivierJM** [comment]
give me sometime i will let you know, though it is running on my end.

**Comment by abnios** [comment]
@OlivierJM  Really Sorry..., The problem was with me I wasn't set the server host address on my device which is on:
 Dev Settings → Debug server host for device Then Type the server machine Ip address with the port  which is like ... (172.*.*.*:3000)
but after listing the unit items list it is not working..., Am I correct, I think this is related to issue #2 ?

**Comment by OlivierJM** [comment]
Yeah nothing much is working so far, but I am putting all things together.

**Comment by OlivierJM** [comment]
@abnios I managed to read different Pdfs from the server on both the emulator and the device, it is a lot of work using the native modules but it is worthy trying. 
I have pushed the latest to the Native branch, I will be working to get Videos and Images displaying too  then the rest can just be styling and configuring for better experience, I have high this will be achievable.
