### ISSUE TITLE
Disable Unit test in GitHub actions

### ISSUE THREAD

**Issue by dennism501** [SparkEdUAB/sparked-mobile#18]
The unit tests in github actions are failing because the `/node_modules` are being included in the files that are being tested by jest. So for this no to hinder progress, we need to disable the tests in the actions.

**Comment by OlivierJM** [comment]
@dennism501 I think this should be related to this #3

**Comment by dennism501** [comment]
Yes it is, so I shouldn't create a separate issue for it?

**Comment by OlivierJM** [comment]
> Yes it is, so I shouldn't create a separate issue for it?

Yeah you can go ahead and disable them and close this issue for now.

**Comment by dennism501** [comment]
Okay cool, let me do that.
