### ISSUE TITLE
create an onboarding screen

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/sparked-mobile#4]
This is will probably be the first screen to be created, things to keep in mind. 
- make sure it matches the designs
- on this screen we need to have a way of connecting to the server
- proper structure will need to be considered

**Comment by dennism501** [comment]
@OlivierJM is this screen this one in the designs? 
![image](https://user-images.githubusercontent.com/15628660/96573391-5bf0c200-12ce-11eb-9128-f41969587821.png)

**Comment by OlivierJM** [comment]
Yes this is the one.

**Comment by dennism501** [comment]
Okay, I can work on this one, the design won't be hard to do, its the logic of a guest user that we will need to discuss further.

**Comment by OlivierJM** [comment]
> Okay, I can work on this one, the design won't be hard to do, its the logic of a guest user that we will need to discuss further.

Ahhh don't worry much about the guest user, we just need to check with the server if the authentication is required or not.

**Comment by dennism501** [comment]
Okay cool, also please ask Stella for the assets on this page, like the color palette and the illustrations in the design so I can add them on the page

**Comment by OlivierJM** [comment]
@MwanahamuntuStarr can you help out with this ?

**Comment by MwanahamuntuStarr** [comment]
Oh my god it took me ages to find this comment am embarrassed. I will send everything through today

**Comment by OlivierJM** [comment]
> Oh my god it took me ages to find this comment am embarrassed. I will send everything through today

No worries @MwanahamuntuStarr, @dennism501 please find the resources here https://github.com/SparkEdUAB/sparked-mobile/issues/1#issuecomment-716040957

**Comment by dennism501** [comment]
Thank you, I will get right on it!

**Comment by dennism501** [comment]
Hey @OlivierJM can we also add the Logo to the #1 with the other assets

**Comment by OlivierJM** [comment]
Adding @MwanahamuntuStarr in the loop on that. 

I had not initially discussed logos with Stella am not sure if we can use the current logo, there is this here https://sparkeduab.github.io/sparked-manual/img/sp6.png it can be used in the meanwhile 

@MwanahamuntuStarr your insights on this, will be highly appreciated

**Comment by dennism501** [comment]
Okay, I will just add a place holder. Also, did we agree on a folder structure?

**Comment by OlivierJM** [comment]
> Okay, I will just add a place holder. Also, did we agree on a folder structure?

Not yet, I was waiting for #8 since it might have conflicting changes, but you can go ahead and structure a basic one like this. 

- components(anything that can be reused)
- screens(any user facing components)

**Comment by dennism501** [comment]
![image](https://user-images.githubusercontent.com/15628660/98312729-00674980-1fdb-11eb-9a00-512b4a740651.png)

Hey, @OlivierJM I have created the screen for this page, how is it so far, before I make a PR?

**Comment by dennism501** [comment]
@MwanahamuntuStarr can you also have a look at it?

**Comment by OlivierJM** [comment]
You can create a merge request then we review it together from there.
Also make sure you rebase with the main branch since there are new changes. 
Otherwise it looks good.
