### ISSUE TITLE
create a login page

### ISSUE THREAD

**Issue by OlivierJM** [SparkEdUAB/sparked-mobile#5]
login page is very optional as some institution won't require users to be logged in, the designs are already there for this.

**Comment by YoramGondwe** [comment]
I will take up this issue

**Comment by OlivierJM** [comment]
awesome, thanks a lot @YoramGondwe check #1 for some guidelines. @dennism501 anything else to add here

**Comment by dennism501** [comment]
@OlivierJM  What library have we decided to use for the components?

**Comment by OlivierJM** [comment]
> @OlivierJM What library have we decided to use for the components?

I thought you were on that 😀

**Comment by dennism501** [comment]
Well i settled on https://docs.nativebase.io/, it has all the components we need and can also customize them with CSS, so I think we can use that one.

**Comment by OlivierJM** [comment]
That sounds good to me, @YoramGondwe check that.

**Comment by YoramGondwe** [comment]
i was actually using that already

**Comment by OlivierJM** [comment]
@YoramGondwe how is this going ?

**Comment by YoramGondwe** [comment]
i think this issue is closed @OlivierJM

**Comment by OlivierJM** [comment]
closing now
